name: Publish PyPI

on:
  push:
    tags:
      - 'v0.1.1'  # Publie sur tous les tags de version

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # n√©cessaire pour pouvoir pousser

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade packaging tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine build

      - name: Build package
        run: python -m build

      - name: Commit build artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Add built distributions for ${{ github.ref_name }}"
          git push origin HEAD:${{ github.ref_name }}

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
